import people from "./Esfahan/people.js";

GetTotalPrice();
FreeDebtors();
// console.log("Generated by DOWNG bitches");
// GetTotalPriceCategory();

function GetTotalPrice() {
  let totalPrice = 0;
  for (const person of people) {
    for (const transaction of person.transactions) {
      for (const item of transaction.items) {
        totalPrice += item.price;
      }
    }
  }
  console.log("خرج کلی", `${totalPrice} تومن شده`);
}

function GetTotalPriceCategory() {
  let categories = [];
  for (const person of people) {
    for (const transaction of person.transactions) {
      let what = categories.some(
        (category) => category.name !== transaction.category
      );
      if (what) {
        categories.push({ name: transaction.category, price: 0 });
      }
      for (const item of transaction.items) {
        // console.log(item);
      }
    }
  }

  console.log(categories);
}

function GetAllSpent() {
  const prices = new Array(6).fill(0);

  for (const person of people) {
    for (const transaction of person.transactions) {
      for (const item of transaction.items) {
        for (const user of item.users) {
          prices[user - 1] += item.price / item.users.length;
        }
      }
    }
  }

  return prices;
}

function GetAllBought() {
  const prices = new Array(6).fill(0);

  for (const person of people) {
    for (const transaction of person.transactions) {
      for (const item of transaction.items) {
        prices[people.indexOf(person)] += item.price;
      }
    }
  }

  return prices;
}

function Calculate() {
  const spent = GetAllSpent();
  const bought = GetAllBought();
  const dec = [];
  const debtors = [];
  const creditors = [];
  for (const index in spent) {
    const difference = bought[index].toFixed(0) - spent[index].toFixed(0);
    const obj = {
      id: index,
      name: people[index].name,
      name_fn: people[index].name_fn,
      price: difference,
    };
    difference > 0 ? creditors.push(obj) : debtors.push(obj);
    dec[index] = obj;

    console.log(
      people[index].name_fn,
      `${spent[index].toFixed(0)} خرجش شده ${bought[index]} خرج کرده`,
      difference > 0
        ? `${difference} باید بگیره`
        : `${Math.abs(difference)} باید بده`
    );
  }

  return { debtors: debtors, creditors: creditors };
}

function FreeDebtors() {
  const data = Calculate();
  const debtors = data.debtors;
  const creditors = data.creditors;

  for (let i = 0; creditors.length - 1 > i; ) {
    for (let j = 0; debtors.length > j; ) {
      if (creditors[i].price + debtors[j].price >= 0) {
        creditors[i].price = creditors[i].price + debtors[j].price;
        console.log(
          `${debtors[j].name_fn} باید ${Math.abs(debtors[j].price)} تومن به ${
            creditors[i].name_fn
          } بده`
        );
        debtors[j].price = 0;
        j++;
      } else {
        debtors[j].price = creditors[i].price + debtors[j].price;
        console.log(
          `${debtors[j].name_fn} باید ${creditors[i].price} تومن به ${creditors[i].name_fn} بده`
        );
        creditors[i].price = 0;
        i++;
      }
    }
  }
}

// function CheckSum() {
//   let totalPrice = 0;
//   for (const index in prices) {
//     totalPrice += prices[index];
//   }

//   console.log("CheckSum TotalPrice", totalPrice.toFixed(0));
// }
